### ISSUE TITLE
LED wont blink in pin 60.

### ISSUE THREAD

**Issue by ghost** [noritan/LedBlink#1]
After I flash the firmware into board via USB, it didn't enumerated and at USB Control Central does not show up device name. So I am curious when I probe Multimeter to the pin 60, it wont have any voltage. I am using FX3s.

**Comment by noritan** [comment]
The LedBlink project controls the LED using the GPIF II state machine.  So, O[60] can never be used for this project because O[60] cannot be controlled by the GPIF II.  The project uses GPIO[21](CTL4) to blink the LED.  Please refer the GPIF II project at  LedBlink/LedBlink/ledblink.cydsn/ledblink.cyfx It is better to open the file with the GPIF II Designer because it is an XML format file for machine readable purpose.

**Comment by ghost** [comment]
May I know where is the hardware pin for the GPIO 21? I read from manual, the GPIO(21) is CTL4 which at pin 60 on GPIF II interface right? But when i check the voltage. it only 0.1mV

**Comment by noritan** [comment]
If you are using FX3S, the package should be 121 pin BGA and there is no "60" pin.
The GPIO[21] is assigned to "G7" on 121 pin BGA.

**Comment by ghost** [comment]
Hi, problem solved, I am using FX3S FPGA from Pactron, the pin have some different build. I found it and now i able to edit it.

1 more question, is it able to make this GPIF II state start only when i receive a vendor command from host? Or in certain condition, the state machine only start?

Thanks.

**Comment by noritan** [comment]
If you want to control the state machine from the firmware, there are two methods as follows.

1) Make a state transition
There is an API function "CyU3PReturnStatus_t CyU3PGpifSMSwitch ( uint16_t fromState, uint16_t toState, uint16_t endState, uint8_t initialAlpha, uint32_t switchTimeout )" to make a state transition. You can make a transition to any states even if the state is disconnected from other state machines.

2) Send trigger to the state machine
In the "Transition Equation Entry" dialogue, there is a signal named "FW_TRG" to receive a trigger signal issued by the firmware using the API function "void CyU3PGpifControlSWInput ( CyBool_t set )"

Please refer the API Guide for more details.

**Comment by ghost** [comment]
Thanks a lot! I will try it out.
